### ISSUE TITLE
Sugestão

### ISSUE THREAD

**Issue by Jetrom17** [DiegoRamosGomes/tabnews-app#24]
Muito bom, adiciona screenshot para usuários novos poderem checar antes de experimentar ou saber o que estão experimentando com expectativa do resultado final. 

Bem, a otimização no expo usando scroll ficou com delay.

**Comment by DiegoRamosGomes** [comment]
Opa mano, beleza? Na verdade o projeto está sendo descontinuado devido minha falta de tempo em mexer nele, o repositório irá ficar público caso alguém queira dar continuidade eu revisarei e aceitarei os pull requests porém não irei mais trabalhar em implementações novas para o projeto
